return {
  ensure_installed = {
    "pyright",
    "mypy",
    "ruff",
    "black",
    "debugpy",
    "rust-analyzer",
    "codelldb",
    "xmlformatter",
    "yaml-language-server",
    "json-lsp",
    "grammarly-languageserver",
    "lua-language-server",
    "stylua",
    "html-lsp",
    "prettier",
    "isort",
    "shellcheck",
    "bash-language-server",
    "texlab",
  },
}
